import {createAction} from '../../utils/redux'

export const ACTION_TYPES = {
    FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
    FETCH_INITIAL_DATA_SUCCESS: 'FETCH_INITIAL_DATA_SUCCESS',
    FETCH_INITIAL_DATA_FAIL: 'FETCH_INITIAL_DATA_FAIL',

    FETCH_SHIPMENT: 'FETCH_SHIPMENT',
    FETCH_SHIPMENT_SUCCESS: 'FETCH_SHIPMENT_SUCCESS',
    FETCH_SHIPMENT_FAIL: 'FETCH_SHIPMENT_FAIL'
}

export const fetchShipment = shipmentNumber => createAction(ACTION_TYPES.FETCH_SHIPMENT, shipmentNumber);